name: Deploy to Hostinger

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    name: Build Angular & Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Producción
        if: github.ref == 'refs/heads/main'
        run: npm run build:prod

      - name: Build Pruebas
        if: github.ref == 'refs/heads/develop'
        run: npx ng build -c pruebas

      - name: Package dist files
        run: tar -czf dist.tar.gz -C dist/pedidos/browser .

      - name: Upload archive to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 65002
          source: "dist.tar.gz"
          target: "~/"

      - name: Deploy Producción en servidor
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 65002
          script: |
            rm -rf ${{ secrets.SSH_TARGET_ADMIN }}/*
            tar -xzf ~/dist.tar.gz -C ${{ secrets.SSH_TARGET_ADMIN }}
            rm ~/dist.tar.gz
            echo "✅ Deploy PRODUCCIÓN completado"

      - name: Deploy Pruebas en servidor
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 65002
          script: |
            rm -rf ${{ secrets.SSH_TARGET_ADMIN_DEV }}/*
            tar -xzf ~/dist.tar.gz -C ${{ secrets.SSH_TARGET_ADMIN_DEV }}
            rm ~/dist.tar.gz
            echo "✅ Deploy PRUEBAS completado"
